version: '3.5'

services:
  api1: &api
    image: juniorleaoo/rinha-backend-java:latest
    hostname: api1
    depends_on:
      - db
      - cache
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATA_REDIS_HOST=cache
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'

  api2:
    <<: *api

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.25GB'

  db:
    image: postgres:latest
    command: 'postgres  -c synchronous_commit=off -c shared_buffers=256MB -c max_connections=200'
    hostname: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'

  cache:
    hostname: cache
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.25GB'

networks:
  default:
    driver: bridge
    name: apps